# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#

# update secret-env-cypher locally with:
# openssl aes-256-cbc -e -in secret-env-plain -out secret-env-cipher -k $KEY
version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          command: |

            openssl aes-256-cbc -d -in secret-env-cipher -k $KEY >> ~/.circlerc
            sudo apt-get update; sudo apt-get install gettext
            npm install -g grunt-cli gh
            GITHUB_TOKEN=$GITHUB_TOKEN GITHUB_USER=$GITHUB_USER node scripts/ci-creds.js
            mkdir -p ~/.config/configstore/
            echo optOut: true > ~/.config/configstore/insight-gh.yml
            cat ~/.ssh/config
            rm  ~/.ssh/config
            git config --global user.email "bugmirror@restmail.net"
            git config --global user.name "Bug Mirror"
            git remote rm origin
            git remote add origin git@github.com:bug-mirror/fxa-content-server-l10n.git

            ssh-agent -s > ~/.ssh_agent_conf;
            source ~/.ssh_agent_conf;

            ssh-add -D;
            openssl aes-256-cbc -d -in id_bug_mirror.enc -k $KEY >> ~/.ssh/id_bug_mirror;
            chmod 0600 ~/.ssh/id_bug_mirror;
            ssh-add ~/.ssh/id_bug_mirror;

            if [ -n "${RUN_NIGHTLY_BUILD}" ]; then
              bash ./scripts/extract-and-pull-request.sh; gh pr --submit mozilla --branch master --browser false;
            fi

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build-test-push:
    jobs:
      - build
